import { formatPHP } from "@/lib/money";

export async function downloadReceiptPdf(row: {
  id: string;
  amount: number;
  currency?: string | null;
  method?: string | null;
  reference?: string | null;
  note?: string | null;
  occurred_on: string;
  finance_categories?: { name?: string } | null;
  churches?: { name?: string } | null;
  members?: { first_name?: string; last_name?: string; email?: string | null; phone?: string | null } | null;
}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a5" });
  const width = doc.internal.pageSize.getWidth();
  const marginX = 32;
  let y = 44;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Official Receipt", marginX, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`No. ${row.id.slice(0, 8).toUpperCase()}`, width - marginX, y, { align: "right" });
  y += 18;

  doc.setTextColor(0);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(row.churches?.name ?? "Church", marginX, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Issued ${new Date().toLocaleString()}`, marginX, y);
  y += 22;

  doc.setDrawColor(220);
  doc.line(marginX, y, width - marginX, y);
  y += 18;

  const rows: [string, string][] = [
    ["Received from", row.members ? `${row.members.first_name ?? ""} ${row.members.last_name ?? ""}`.trim() : "Anonymous"],
    ["Date", new Date(row.occurred_on).toLocaleDateString()],
    ["Category", row.finance_categories?.name ?? "—"],
    ["Method", row.method ?? "—"],
    ["Reference", row.reference ?? "—"],
  ];
  doc.setTextColor(0);
  doc.setFontSize(10);
  for (const [k, v] of rows) {
    doc.setTextColor(130);
    doc.text(k, marginX, y);
    doc.setTextColor(0);
    doc.text(String(v ?? "—"), marginX + 100, y);
    y += 16;
  }

  y += 8;
  doc.setDrawColor(220);
  doc.line(marginX, y, width - marginX, y);
  y += 22;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Amount", marginX, y);
  doc.text(formatPHP(row.amount), width - marginX, y, { align: "right" });
  y += 20;

  if (row.note) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text("Note", marginX, y);
    y += 12;
    doc.setTextColor(0);
    const lines = doc.splitTextToSize(row.note, width - marginX * 2);
    doc.text(lines, marginX, y);
    y += 12 * lines.length;
  }

  y = doc.internal.pageSize.getHeight() - 40;
  doc.setFontSize(8);
  doc.setTextColor(140);
  doc.text("Thank you for your generosity.", marginX, y);
  doc.text("This receipt was generated by Church OS.", width - marginX, y, { align: "right" });

  doc.save(`receipt-${row.id.slice(0, 8)}.pdf`);
}