/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisitorsRouteImport } from './routes/_authenticated/visitors'
import { Route as AuthenticatedVisitationRouteImport } from './routes/_authenticated/visitation'
import { Route as AuthenticatedSundaySchoolRouteImport } from './routes/_authenticated/sunday-school'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedMinistryRouteImport } from './routes/_authenticated/ministry'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDiscipleshipRouteImport } from './routes/_authenticated/discipleship'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommitteeRouteImport } from './routes/_authenticated/committee'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings.organization'
import { Route as AuthenticatedSettingsChurchesRouteImport } from './routes/_authenticated/settings.churches'
import { Route as AuthenticatedMembersNewRouteImport } from './routes/_authenticated/members.new'
import { Route as AuthenticatedMembersIdRouteImport } from './routes/_authenticated/members.$id'
import { Route as AuthenticatedFinanceReportsRouteImport } from './routes/_authenticated/finance_.reports'
import { Route as AuthenticatedFinancePledgesRouteImport } from './routes/_authenticated/finance_.pledges'
import { Route as AuthenticatedFinanceMemberReportsRouteImport } from './routes/_authenticated/finance_.member-reports'
import { Route as AuthenticatedFinanceContributionsRouteImport } from './routes/_authenticated/finance_.contributions'
import { Route as AuthenticatedEventsRegisterRouteImport } from './routes/_authenticated/events/register'
import { Route as AuthenticatedEventsIdRouteImport } from './routes/_authenticated/events/$id'
import { Route as AuthenticatedFinanceMembersIdRouteImport } from './routes/_authenticated/finance_.members.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitorsRoute = AuthenticatedVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitationRoute = AuthenticatedVisitationRouteImport.update({
  id: '/visitation',
  path: '/visitation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSundaySchoolRoute =
  AuthenticatedSundaySchoolRouteImport.update({
    id: '/sunday-school',
    path: '/sunday-school',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinistryRoute = AuthenticatedMinistryRouteImport.update({
  id: '/ministry',
  path: '/ministry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscipleshipRoute =
  AuthenticatedDiscipleshipRouteImport.update({
    id: '/discipleship',
    path: '/discipleship',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitteeRoute = AuthenticatedCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsChurchesRoute =
  AuthenticatedSettingsChurchesRouteImport.update({
    id: '/churches',
    path: '/churches',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedMembersNewRoute = AuthenticatedMembersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedMembersRoute,
} as any)
const AuthenticatedMembersIdRoute = AuthenticatedMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMembersRoute,
} as any)
const AuthenticatedFinanceReportsRoute =
  AuthenticatedFinanceReportsRouteImport.update({
    id: '/finance_/reports',
    path: '/finance/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePledgesRoute =
  AuthenticatedFinancePledgesRouteImport.update({
    id: '/finance_/pledges',
    path: '/finance/pledges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceMemberReportsRoute =
  AuthenticatedFinanceMemberReportsRouteImport.update({
    id: '/finance_/member-reports',
    path: '/finance/member-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceContributionsRoute =
  AuthenticatedFinanceContributionsRouteImport.update({
    id: '/finance_/contributions',
    path: '/finance/contributions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRegisterRoute =
  AuthenticatedEventsRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedEventsIdRoute = AuthenticatedEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEventsRoute,
} as any)
const AuthenticatedFinanceMembersIdRoute =
  AuthenticatedFinanceMembersIdRouteImport.update({
    id: '/finance_/members/$id',
    path: '/finance/members/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discipleship': typeof AuthenticatedDiscipleshipRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/ministry': typeof AuthenticatedMinistryRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/sunday-school': typeof AuthenticatedSundaySchoolRoute
  '/visitation': typeof AuthenticatedVisitationRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/events/register': typeof AuthenticatedEventsRegisterRoute
  '/finance/contributions': typeof AuthenticatedFinanceContributionsRoute
  '/finance/member-reports': typeof AuthenticatedFinanceMemberReportsRoute
  '/finance/pledges': typeof AuthenticatedFinancePledgesRoute
  '/finance/reports': typeof AuthenticatedFinanceReportsRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/members/new': typeof AuthenticatedMembersNewRoute
  '/settings/churches': typeof AuthenticatedSettingsChurchesRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/finance/members/$id': typeof AuthenticatedFinanceMembersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discipleship': typeof AuthenticatedDiscipleshipRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/ministry': typeof AuthenticatedMinistryRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/sunday-school': typeof AuthenticatedSundaySchoolRoute
  '/visitation': typeof AuthenticatedVisitationRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/events/register': typeof AuthenticatedEventsRegisterRoute
  '/finance/contributions': typeof AuthenticatedFinanceContributionsRoute
  '/finance/member-reports': typeof AuthenticatedFinanceMemberReportsRoute
  '/finance/pledges': typeof AuthenticatedFinancePledgesRoute
  '/finance/reports': typeof AuthenticatedFinanceReportsRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/members/new': typeof AuthenticatedMembersNewRoute
  '/settings/churches': typeof AuthenticatedSettingsChurchesRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/finance/members/$id': typeof AuthenticatedFinanceMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/committee': typeof AuthenticatedCommitteeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discipleship': typeof AuthenticatedDiscipleshipRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/_authenticated/ministry': typeof AuthenticatedMinistryRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/sunday-school': typeof AuthenticatedSundaySchoolRoute
  '/_authenticated/visitation': typeof AuthenticatedVisitationRoute
  '/_authenticated/visitors': typeof AuthenticatedVisitorsRoute
  '/_authenticated/events/$id': typeof AuthenticatedEventsIdRoute
  '/_authenticated/events/register': typeof AuthenticatedEventsRegisterRoute
  '/_authenticated/finance_/contributions': typeof AuthenticatedFinanceContributionsRoute
  '/_authenticated/finance_/member-reports': typeof AuthenticatedFinanceMemberReportsRoute
  '/_authenticated/finance_/pledges': typeof AuthenticatedFinancePledgesRoute
  '/_authenticated/finance_/reports': typeof AuthenticatedFinanceReportsRoute
  '/_authenticated/members/$id': typeof AuthenticatedMembersIdRoute
  '/_authenticated/members/new': typeof AuthenticatedMembersNewRoute
  '/_authenticated/settings/churches': typeof AuthenticatedSettingsChurchesRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/finance_/members/$id': typeof AuthenticatedFinanceMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/committee'
    | '/dashboard'
    | '/discipleship'
    | '/events'
    | '/finance'
    | '/inventory'
    | '/members'
    | '/ministry'
    | '/outreach'
    | '/settings'
    | '/sunday-school'
    | '/visitation'
    | '/visitors'
    | '/events/$id'
    | '/events/register'
    | '/finance/contributions'
    | '/finance/member-reports'
    | '/finance/pledges'
    | '/finance/reports'
    | '/members/$id'
    | '/members/new'
    | '/settings/churches'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/team'
    | '/events/'
    | '/members/'
    | '/settings/'
    | '/finance/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/committee'
    | '/dashboard'
    | '/discipleship'
    | '/finance'
    | '/inventory'
    | '/ministry'
    | '/outreach'
    | '/sunday-school'
    | '/visitation'
    | '/visitors'
    | '/events/$id'
    | '/events/register'
    | '/finance/contributions'
    | '/finance/member-reports'
    | '/finance/pledges'
    | '/finance/reports'
    | '/members/$id'
    | '/members/new'
    | '/settings/churches'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/team'
    | '/events'
    | '/members'
    | '/settings'
    | '/finance/members/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/committee'
    | '/_authenticated/dashboard'
    | '/_authenticated/discipleship'
    | '/_authenticated/events'
    | '/_authenticated/finance'
    | '/_authenticated/inventory'
    | '/_authenticated/members'
    | '/_authenticated/ministry'
    | '/_authenticated/outreach'
    | '/_authenticated/settings'
    | '/_authenticated/sunday-school'
    | '/_authenticated/visitation'
    | '/_authenticated/visitors'
    | '/_authenticated/events/$id'
    | '/_authenticated/events/register'
    | '/_authenticated/finance_/contributions'
    | '/_authenticated/finance_/member-reports'
    | '/_authenticated/finance_/pledges'
    | '/_authenticated/finance_/reports'
    | '/_authenticated/members/$id'
    | '/_authenticated/members/new'
    | '/_authenticated/settings/churches'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/team'
    | '/_authenticated/events/'
    | '/_authenticated/members/'
    | '/_authenticated/settings/'
    | '/_authenticated/finance_/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visitors': {
      id: '/_authenticated/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AuthenticatedVisitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visitation': {
      id: '/_authenticated/visitation'
      path: '/visitation'
      fullPath: '/visitation'
      preLoaderRoute: typeof AuthenticatedVisitationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sunday-school': {
      id: '/_authenticated/sunday-school'
      path: '/sunday-school'
      fullPath: '/sunday-school'
      preLoaderRoute: typeof AuthenticatedSundaySchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ministry': {
      id: '/_authenticated/ministry'
      path: '/ministry'
      fullPath: '/ministry'
      preLoaderRoute: typeof AuthenticatedMinistryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discipleship': {
      id: '/_authenticated/discipleship'
      path: '/discipleship'
      fullPath: '/discipleship'
      preLoaderRoute: typeof AuthenticatedDiscipleshipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee': {
      id: '/_authenticated/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof AuthenticatedCommitteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/churches': {
      id: '/_authenticated/settings/churches'
      path: '/churches'
      fullPath: '/settings/churches'
      preLoaderRoute: typeof AuthenticatedSettingsChurchesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/members/new': {
      id: '/_authenticated/members/new'
      path: '/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof AuthenticatedMembersNewRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/members/$id': {
      id: '/_authenticated/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AuthenticatedMembersIdRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/finance_/reports': {
      id: '/_authenticated/finance_/reports'
      path: '/finance/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof AuthenticatedFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/pledges': {
      id: '/_authenticated/finance_/pledges'
      path: '/finance/pledges'
      fullPath: '/finance/pledges'
      preLoaderRoute: typeof AuthenticatedFinancePledgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/member-reports': {
      id: '/_authenticated/finance_/member-reports'
      path: '/finance/member-reports'
      fullPath: '/finance/member-reports'
      preLoaderRoute: typeof AuthenticatedFinanceMemberReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/contributions': {
      id: '/_authenticated/finance_/contributions'
      path: '/finance/contributions'
      fullPath: '/finance/contributions'
      preLoaderRoute: typeof AuthenticatedFinanceContributionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/register': {
      id: '/_authenticated/events/register'
      path: '/register'
      fullPath: '/events/register'
      preLoaderRoute: typeof AuthenticatedEventsRegisterRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/events/$id': {
      id: '/_authenticated/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AuthenticatedEventsIdRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/finance_/members/$id': {
      id: '/_authenticated/finance_/members/$id'
      path: '/finance/members/$id'
      fullPath: '/finance/members/$id'
      preLoaderRoute: typeof AuthenticatedFinanceMembersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsIdRoute: typeof AuthenticatedEventsIdRoute
  AuthenticatedEventsRegisterRoute: typeof AuthenticatedEventsRegisterRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsIdRoute: AuthenticatedEventsIdRoute,
  AuthenticatedEventsRegisterRoute: AuthenticatedEventsRegisterRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersIdRoute: typeof AuthenticatedMembersIdRoute
  AuthenticatedMembersNewRoute: typeof AuthenticatedMembersNewRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersIdRoute: AuthenticatedMembersIdRoute,
  AuthenticatedMembersNewRoute: AuthenticatedMembersNewRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsChurchesRoute: typeof AuthenticatedSettingsChurchesRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsChurchesRoute: AuthenticatedSettingsChurchesRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommitteeRoute: typeof AuthenticatedCommitteeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscipleshipRoute: typeof AuthenticatedDiscipleshipRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedMinistryRoute: typeof AuthenticatedMinistryRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSundaySchoolRoute: typeof AuthenticatedSundaySchoolRoute
  AuthenticatedVisitationRoute: typeof AuthenticatedVisitationRoute
  AuthenticatedVisitorsRoute: typeof AuthenticatedVisitorsRoute
  AuthenticatedFinanceContributionsRoute: typeof AuthenticatedFinanceContributionsRoute
  AuthenticatedFinanceMemberReportsRoute: typeof AuthenticatedFinanceMemberReportsRoute
  AuthenticatedFinancePledgesRoute: typeof AuthenticatedFinancePledgesRoute
  AuthenticatedFinanceReportsRoute: typeof AuthenticatedFinanceReportsRoute
  AuthenticatedFinanceMembersIdRoute: typeof AuthenticatedFinanceMembersIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommitteeRoute: AuthenticatedCommitteeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscipleshipRoute: AuthenticatedDiscipleshipRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedMinistryRoute: AuthenticatedMinistryRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSundaySchoolRoute: AuthenticatedSundaySchoolRoute,
  AuthenticatedVisitationRoute: AuthenticatedVisitationRoute,
  AuthenticatedVisitorsRoute: AuthenticatedVisitorsRoute,
  AuthenticatedFinanceContributionsRoute:
    AuthenticatedFinanceContributionsRoute,
  AuthenticatedFinanceMemberReportsRoute:
    AuthenticatedFinanceMemberReportsRoute,
  AuthenticatedFinancePledgesRoute: AuthenticatedFinancePledgesRoute,
  AuthenticatedFinanceReportsRoute: AuthenticatedFinanceReportsRoute,
  AuthenticatedFinanceMembersIdRoute: AuthenticatedFinanceMembersIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
